# Generated by Django 4.0.1 on 2022-01-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tegs',
            new_name='Tags',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'Посты', 'verbose_name_plural': 'Пост'},
        ),
    ]
